---
title: "108-04-19"
output: html_document
---


```{r}
a <- c("1","b","TRUE")
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
length(a)
a[[7]] <- "Jhonson"
a <- c(a,c("Marry"))
a
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

list1[[1]]$birthday <- ymd("1997-03-21")
list1[[2]]<- list(
    name="Marry",
    birthday= ymd("1998-08-24")
)

list1[[2]]$status <-c(height=163, weight=45)
list1[[1]]$status <- 176

str(list1)
```

```{r}
# [] 加子要加母結構的
list1[[1]]$"age" <- 21
list1[[2]]["age"] <- list(23)
str(list1)
```

```{r}
list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)

str(list1)
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
str(listExample)
listExample[["學期"]][[1]][2] <- list(list(
  name= "產業經濟學",
  teacher= "Wen",
  grade=88
  )
)
str(listExample)
```

```{r}
str(listExample)

# 108-1新增一科目成績
listExample$學期$`108-1`[[2]] <-
  list(name="產業經濟學")
str(listExample)

listExample$學期$`108-1`[[2]][c("teacher","grade")] <- 
  list(
    "Wen",
    88
    )
str(listExample)
```

```{r}
print(a)
a[-c(1,3)]
a[c(-2)]

print(a)
a[-c(1,3)] -> a # 要回存才算真的刪除
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    ),
    list(
      name="Mary",
      birthday=ymd("1998-08-24"),
      status=c(height=163, weight=45),
      age=21,
      bloodType="AB"
    )
  )
str(list1)
```

```{r}
# 回存回母元素
list1[[1]][-3] -> list1[[1]]
str(list1)
list1[[2]][-c(4,5)]-> list1[[2]]
str(list1)
```

```{r}
str(list1)
list1[[2]][c(4,5)] <- NULL
str(list1)
```

```{r}
library(jsonlite)
fromJSON("https://data.ntpc.gov.tw/od/data/api/54DDDC93-589C-4858-9C95-18B2046CC1FC?$format=json", simplifyDataFrame = F) -> newTaipeiYouBike

str(newTaipeiYouBike)



```

```{r}
today <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))
tomorrow <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))

weather <- list(today,tomorrow)

str(weather)

weather[[1]][[2]][[2]] #today
weather[[2]][[2]][[2]]

#$ 只適用list

weather[[1]][[2]]$highest_temp # 今天/新北市/highest_temp
weather[[2]][[2]]$"highest_temp" # 明天/新北市/highest_temp
```
















